-- public.users definition

-- Drop table

-- DROP TABLE public.users;

CREATE TABLE public.users (
                              id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
                              created_at timestamptz(6) NOT NULL,
                              username varchar(50) NULL,
                              display_name varchar(100) NULL,
                              profile_image_url varchar(500) NULL,
                              cover_image_url varchar(500) NULL,
                              bio text NULL,
                              email varchar(255) NULL,
                              password_hash varchar(255) NOT NULL,
                              "role" varchar(255) NULL,
                              CONSTRAINT users_email_key UNIQUE (email),
                              CONSTRAINT users_pkey PRIMARY KEY (id),
                              CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['USER'::character varying, 'ADMIN'::character varying])::text[]))),
	CONSTRAINT users_username_key UNIQUE (username)
);


-- public.posts definition

-- Drop table

-- DROP TABLE public.posts;

CREATE TABLE public.posts (
                              id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
                              user_id int4 NOT NULL,
                              created_at timestamptz(6) NOT NULL,
                              image_url varchar(500) NULL,
                              content_text varchar(2000) NULL,
                              CONSTRAINT posts_pkey PRIMARY KEY (id),
                              CONSTRAINT fk5lidm6cqbc7u4xhqpxm898qme FOREIGN KEY (user_id) REFERENCES public.users(id)
);


-- public."comments" definition

-- Drop table

-- DROP TABLE public."comments";

CREATE TABLE public."comments" (
                                   id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                   post_id int4 NOT NULL,
                                   user_id int4 NOT NULL,
                                   created_at timestamptz(6) NOT NULL,
                                   "content" varchar(1000) NULL,
                                   CONSTRAINT comments_pkey PRIMARY KEY (id),
                                   CONSTRAINT fk8omq0tc18jd43bu5tjh6jvraq FOREIGN KEY (user_id) REFERENCES public.users(id),
                                   CONSTRAINT fkh4c7lvsc298whoyd4w9ta25cr FOREIGN KEY (post_id) REFERENCES public.posts(id)
);


-- public.follows definition

-- Drop table

-- DROP TABLE public.follows;

CREATE TABLE public.follows (
                                followed_id int4 NOT NULL,
                                follower_id int4 NOT NULL,
                                created_at timestamptz(6) NOT NULL,
                                CONSTRAINT follows_pkey PRIMARY KEY (followed_id, follower_id),
                                CONSTRAINT fk45sy1jkos9oy1j4by9y7225nm FOREIGN KEY (followed_id) REFERENCES public.users(id),
                                CONSTRAINT fkqnkw0cwwh6572nyhvdjqlr163 FOREIGN KEY (follower_id) REFERENCES public.users(id)
);
