spring.application.name=spring-boot

spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

application.security.jwt.secret-key=${JWT_SECRET}
# 1 day
application.security.jwt.expiration=${JWT_EXPIRATION}
# 7 days
application.security.jwt.refresh-token.expiration=${JWT_REFRESH_EXPIRATION}

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never